### ISSUE TITLE
RuntimeError: Not compiled with GPU support

### ISSUE THREAD

**Issue by cc19860606** [sel118/LaneAF#20]
Traceback (most recent call last):
  File "train_culane.py", line 277, in <module>
    model, avg_loss_seg, avg_loss_vaf, avg_loss_haf, avg_loss, avg_acc, avg_f1 = train(model, i)
  File "train_culane.py", line 89, in train
    outputs = net(input_img)[-1]
  File "/root/miniconda3/envs/laneaf/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/cc/models/dla/pose_dla_dcn.py", line 471, in forward
    x = self.dla_up(x)
  File "/root/miniconda3/envs/laneaf/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/cc/models/dla/pose_dla_dcn.py", line 410, in forward
    ida(layers, len(layers) -i - 2, len(layers))
  File "/root/miniconda3/envs/laneaf/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/cc/models/dla/pose_dla_dcn.py", line 384, in forward
    layers[i] = upsample(project(layers[i]))
  File "/root/miniconda3/envs/laneaf/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/cc/models/dla/pose_dla_dcn.py", line 355, in forward
    x = self.conv(x)
  File "/root/miniconda3/envs/laneaf/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/cc/models/dla/DCNv2/dcn_v2.py", line 170, in forward
    self.deformable_groups,
  File "/home/cc/models/dla/DCNv2/dcn_v2.py", line 37, in forward
    ctx.deformable_groups,
RuntimeError: Not compiled with GPU support
(laneaf) root@cbd2e2a937ad:/home/cc# nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243
Anyone can give me some suggestions?

**Comment by arangesh** [comment]
This seems to be an issue with the DCNv2 build. You can see a similar issue (and possible solution) [here](https://github.com/CharlesShang/DCNv2/issues/82).
