### ISSUE TITLE
Anout laneseg_label_w16_test

### ISSUE THREAD

**Issue by cc19860606** [sel118/LaneAF#21]
There is no laneseg_label_w16_test in CuLane.  How to generate it? 
When i make a empty folder named laneseg_label_w16_test and use "CUDA_VISIBLE_DEVICES=0 python infer_culane.py --dataset-dir=data/CULane/ --snapshot=experiments/culane/2021-05-25-07\:41/net_0032.pth --save-viz", it reports as follow:
Traceback (most recent call last):
  File "infer_culane.py", line 135, in <module>
    test(model)
  File "infer_culane.py", line 76, in test
    for b_idx, sample in enumerate(test_loader):
  File "/root/miniconda3/envs/laneaf/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/root/miniconda3/envs/laneaf/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1085, in _next_data
    return self._process_data(data)
  File "/root/miniconda3/envs/laneaf/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data
    data.reraise()
  File "/root/miniconda3/envs/laneaf/lib/python3.6/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/root/miniconda3/envs/laneaf/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/root/miniconda3/envs/laneaf/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/miniconda3/envs/laneaf/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/cc/datasets/culane.py", line 128, in __getitem__
    seg = np.tile(seg[..., np.newaxis], (1, 1, 3)) # (H, W, 3)
TypeError: 'NoneType' object is not subscriptable

**Comment by arangesh** [comment]
You can generate it using [this repo](https://github.com/XingangPan/seg_label_generate).
