### ISSUE TITLE
How to test my own images?

### ISSUE THREAD

**Issue by Meaw0415** [sel118/LaneAF#29]
I think your work is very great. And I tried to use the pre-trained model to test my own images. I used the code in issue#5 but I have some errors. 
![image](https://user-images.githubusercontent.com/88161103/127548236-5423da69-fcfa-4cf3-af12-3ed6c47c17ba.png)

Traceback (most recent call last):
  File "/home/shy/lanedet_code/LaneAF-main/test.py", line 158, in <module>
    test(model)
  File "/home/shy/lanedet_code/LaneAF-main/test.py", line 97, in test
    input_img = img_transforms(img)
  File "/usr/local/anaconda3/envs/lane/lib/python3.6/site-packages/torchvision/transforms/transforms.py", line 67, in __call__
    img = t(img)
  File "/usr/local/anaconda3/envs/lane/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/anaconda3/envs/lane/lib/python3.6/site-packages/torchvision/transforms/transforms.py", line 823, in forward
    i, j, h, w = self.get_params(img, self.scale, self.ratio)
  File "/usr/local/anaconda3/envs/lane/lib/python3.6/site-packages/torchvision/transforms/transforms.py", line 782, in get_params
    width, height = F._get_image_size(img)
  File "/usr/local/anaconda3/envs/lane/lib/python3.6/site-packages/torchvision/transforms/functional.py", line 32, in _get_image_size
    return F_pil._get_image_size(img)
  File "/usr/local/anaconda3/envs/lane/lib/python3.6/site-packages/torchvision/transforms/functional_pil.py", line 26, in _get_image_size
    raise TypeError("Unexpected type {}".format(type(img)))
TypeError: Unexpected type <class 'numpy.ndarray'>

When I ignored the transform, the output file is wrong. The txt file has 24or23 lines which should have only 4 lines.

**Comment by arangesh** [comment]
The `mean` and `std` arguments for `transforms.Normalize` are incorrect. Since you are not using group transformations, you only need to pass in the first entry of the `mean` and `std` tuple that you currently have: `self.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])`.

Similarly, for `transforms.RandomResizedCrop`, you need to modify the `size` and `scale` arguments so that output image is resized by half. Else, you could make use of `transforms.Resize` instead. Finally, if nothing else works, I would highly suggest you use the original group transformations as shown [here](https://github.com/sel118/LaneAF/blob/8cf6dd62f0e52bda3e9b1e221ab0b371d31b6c9d/datasets/culane.py#L146).
